## 파이토치 기본

### 파이토치 공식 튜토리얼
- https://tutorials.pytorch.kr/
### 파이토치 패키지(API)
- torch : 메인 네임스페이스. 텐서(기본단위) 등 수학함수를 포함. Numpy와 유사한 구조.
- torch.autograd : 자동미분을 위한 함수들이 포함. 컨텍스트 매니저, 기반클래스 포함
- torch.nn/ torch.nn.functional : neuralnetwork. 신경망 구축위한 데이터 구조, 레이어 등이 정의되어 있느 모듈. ReLU 등도 포함
- torch.optim : SGD(확률적 경사 하강법) 중심 파라미터 최적화 알고리즘 포함
- torch.utils : SGD  반복 연산 시 배치용 유틸리티 함수 포함
- torch.multiprocessing : 파이토치용 병렬프로세싱 환경을 안전하게 다루기 위한 모듈

### 텐서
- 파이토치 기본단위
    - 1차원 배열 - 벡터
    - 2차원 배열 - 행렬(매트릭스)
    - 3차원 배열 - 텐서
- <img src ='./파이토치_텐서.png' width = "500">
- <img src ='./파이토치_텐서2.png' width = "500">

In [1]:
import torch

In [2]:
t1 = torch.tensor([1.0,2.0,3.0])
t1

tensor([1., 2., 3.])

In [14]:
print(t1.shape)     # 텐서크기
print(t1.dtype)      # 텐서자료형
print(t1.type())    # 텐서자료형 + 전체타입
print(t1.device)    # 어느 디바이스에서 사용중인지

torch.Size([3])
torch.float32
torch.FloatTensor
cpu


In [3]:
import numpy as np
n1 = np.array([1.0,2.0,3.0])
n1

array([1., 2., 3.])

In [15]:
print(n1.shape)
print(n1.dtype)


(3,)
float64


- 넘파이의 배열이랑 torch의 텐서랑 거의 차이 없다.

In [5]:
## numpy에서 1, 0 으로 초기화 되는
n2 = np.ones([2,3])
n2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
n3 = np.zeros([2,3])
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
t2 = torch.ones([2,3])
t2

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
print(t2.shape)     # 텐서크기
print(t2.dtype)      # 텐서자료형
print(t2.type())    # 텐서자료형 + 전체타입
print(t2.device)    # 어느 디바이스에서 사용중인지

torch.Size([2, 3])
torch.float32
torch.FloatTensor
cpu


In [8]:
t3 = torch.zeros([2,3])
t3

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# numpy로 만든 배열을 텐서로 변환
t4 = torch.from_numpy(n3)
t4

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

- 넘파이 배열과 파이토치 텐서간의 형변환 아주 쉽다

In [17]:
t5 = torch.ones(3,3,3)
t5

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [18]:
print(t5.shape)     # 텐서크기
print(t5.dtype)      # 텐서자료형
print(t5.type())    # 텐서자료형 + 전체타입
print(t5.device)    # 어느 디바이스에서 사용중인지

torch.Size([3, 3, 3])
torch.float32
torch.FloatTensor
cpu


In [31]:
# 랜덤값
# 함수	분포 형태	값의 범위
#torch.rand()	균등분포 (Uniform)	[0.0, 1.0) 사이
#torch.randn()	정규분포 (Normal)	평균 0, 표준편차 1 (가우시안 분포)
t6 = torch.rand(2,3)
t6

tensor([[0.2866, 0.4973, 0.0261],
        [0.8681, 0.6147, 0.8628]])

#### cpu에 있는 텐서를 cuda로 이동

In [19]:
device =  torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [20]:
# t5(cpu)에 있는 텐서를 cuda로
# 변수명을 같게 하면 이동
# 변수명을 다르게 하면 복사

# 이동
t5 = t5.to(device=device)

In [21]:
print(t5.shape)     # 텐서크기
print(t5.dtype)      # 텐서자료형
print(t5.type())    # 텐서자료형 + 전체타입
print(t5.device)    # 어느 디바이스에서 사용중인지

torch.Size([3, 3, 3])
torch.float32
torch.cuda.FloatTensor
cuda:0


- cuda(GPU사용하는 것) : 0 (그래픽카드 다수일 수 있음)

#### GPU 사용법

In [24]:
import torch.nn

# cpu사용하는 신경망 모델 생성(3개의 입력을 넣어서 하나의 출력을 내는 신경망)
model = torch.nn.Linear(3, 1)                    #입력featuer 3, 출력feature 1

sample_input = torch.tensor([[1.0,2.0,3.0]])
sample_input.shape                              #torch.Size([1, 3])  2차원 배열

torch.Size([1, 3])

In [25]:
output = model(sample_input)
output

tensor([[-0.7023]], grad_fn=<AddmmBackward0>)

In [28]:
# cuda 사용하는 신경망 모델 생성(3개의 입력을 넣어서 하나의 출력을 내는 신경망)
model2 = torch.nn.Linear(3, 1)                    #입력featuer 3, 출력feature 1
model2.to(device)
sample_input2 = torch.tensor([[1.0,2.0,3.0]]).to(device)
output2 = model2(sample_input2)
output2

tensor([[2.2340]], device='cuda:0', grad_fn=<AddmmBackward0>)

### 파이토치 모델 학습
- torch.nn.Module로 신경망 모델 만들기
- 손실함수, 옵티마이저 설정 학습
- 학습 루프 기본 구조 학습

#### 기본구조 추가


In [32]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [34]:
# 모델 선언(클래스)
class SimpleNet(nn.Module):                         # nn.Module 클래스를 상속해서 클래스 생성
    def __init__(self):
        super( SimpleNet, self).__init__()
        # Linear : Dense Layer(텐서플로 케라스의 밀집층) 과 유사
        self.fc1 = nn.Linear(4,16)                  #input : 4개 차원, output : 16개 뉴런
        self.fc2  = nn.Linear(16,3)                 #output  : 3개 차원 클래스(3가지 분류 예측)

    def forward(self, x):                           #실제 연산이 수행되는 함수(자동 호출)
        x = F.relu(self.fc1(x))                     #첫번째 레이어 통과 하면서 활성화함수(시그모이드, 소프트맥스, 렐루 모두 존재)
        x = self.fc2(x)                             #두번째 레이어는 출력층이다. 
        return x

- 텐서플로우(케라스)는 중간층에서 입력값을 설정하지 않아도 됨
- 파이토치는 입력값과 출력값을 모두 설정

In [35]:
# 모델 확인
model = SimpleNet()
model

SimpleNet(
  (fc1): Linear(in_features=4, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=3, bias=True)
)

In [38]:
# 샘플입력값
x = torch.rand(1,4)
x

tensor([[0.6234, 0.1162, 0.8355, 0.3167]])

In [39]:
out = model(x)
out

tensor([[-0.1903, -0.0752, -0.2294]], grad_fn=<AddmmBackward0>)

#### 손실함수/옵티마이저 설정

In [40]:
#분류(마지막 출력 3개)
criterion = nn.CrossEntropyLoss()

#옵티마이저(Adam)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)         #lr(learning rate)학습률 : 보통 0.01~0.0001 사이로 지정




#### 1회학습

In [46]:
#정답 레이블(label)**을 텐서로 정의
y = torch.tensor([1])


#Forward

#예측 결과
outputs = model(x)
#모델의 출력 outputs와 정답 y 사이의 **오차(손실)**를 계산.
loss = criterion(outputs, y)



#Backward(역전파) : 뉴런을 통과한 값이 다시 다음 훈련의 입력으로 사용

# 이전 스텝에서 계산된 **gradient(기울기)**를 초기화.
#PyTorch는 기본적으로 gradient를 누적하기 때문에, 매번 초기화가 필요함.
optimizer.zero_grad()  

# loss를 기준으로, 모델 파라미터(가중치 등)에 대한 gradient를 자동 계산.
loss.backward()     

#계산한 gradient를 이용해서 파라미터 업데이트
optimizer.step()         

#텐서 형태의 손실값에서 숫자만 추출
#현재 손실값을 출력
loss.item()

0.7072060108184814

### 데이터셋, 데이터 로더
- `Dataset`, `DataLoader` 학습
- 내장 데이터셋
- 커스텀 데이터셋 만들기
- 배치 학습 처리

#### 데이터셋, 데이터로더란?
- Dataset - 데이터를 불러오는 방법
- DataLoader - 데이터를 배치단위로 나누기, 셔플, 병렬처리 방법

#### 추가
- 머신러닝,딥러닝에 사용되는 데이터샘플 종류 예제

In [51]:
from sklearn.datasets import load_breast_cancer, load_wine     #11개의 데이터셋 존재
import seaborn  as sns

datas = sns.load_dataset('titanic') # https://github.com/mwaskom/seaborn-data 확인

from torchvision.datasets import FashionMNIST, MNIST, CIFAR10       #이미지 데이터 셋
from keras.datasets import mnist, fashion_mnist, boston_housing, cifar10, cifar100, imdb  #이미지, 텍스트 데이터 셋


datas 

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0           0       3    male  22.0  ...   NaN  Southampton     no  False
1           1       1  female  38.0  ...     C    Cherbourg    yes  False
2           1       3  female  26.0  ...   NaN  Southampton    yes   True
3           1       1  female  35.0  ...     C  Southampton    yes  False
4           0       3    male  35.0  ...   NaN  Southampton     no   True
..        ...     ...     ...   ...  ...   ...          ...    ...    ...
886         0       2    male  27.0  ...   NaN  Southampton     no   True
887         1       1  female  19.0  ...     B  Southampton    yes   True
888         0       3  female   NaN  ...   NaN  Southampton     no  False
889         1       1    male  26.0  ...     C    Cherbourg    yes   True
890         0       3    male  32.0  ...   NaN   Queenstown     no   True

[891 rows x 15 columns]

##### 붓꽃(Iris) 데이터셋 사용

In [47]:
#데이터셋 처리 모듈 로드
from sklearn.datasets import load_iris, load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import torch

In [54]:
# 데이터 로드
iris = load_iris()

# 입력(특성)데이터 X , 타겟 y 
X = iris['data']
y = iris['target']

print(X.shape, y.shape) # 넘파이 데이터

(150, 4) (150,)


In [57]:
# sepal(꽃받침) length (cm) | sepal width (cm) | petal(꽃입)length (cm) |  petal width (cm) 
X[0,:]

array([5.1, 3.5, 1.4, 0.2])

In [58]:
# 0(setosa)| 1 (versicolor)| 2(virginica)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [59]:
# 표준화(정규화)
scaler = StandardScaler()
X = scaler.fit_transform(X)


In [60]:
X[0,:]

array([-0.90068117,  1.01900435, -1.34022653, -1.3154443 ])

In [64]:
# 훈련세트, 테스트세트 분리
train_scaled, test_scaled , train_target, test_target =  train_test_split(X, y, test_size=0.2 , random_state=42)

In [65]:
#훈련세트, 검증세트 분리
train_scaled, val_scaled , train_target, val_target =  train_test_split(train_scaled, train_target, test_size=0.2 , random_state=42)

In [67]:
train_scaled.shape

(96, 4)

In [68]:
val_scaled.shape

(24, 4)

In [66]:
test_scaled.shape

(30, 4)

In [70]:
train_target.shape

(96,)

##### 커스텀 데이터셋만들기

In [77]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [78]:
class IrisDataset(Dataset):
    def __init__ (self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)   # 특성(입력)값은 실수
        self.y = torch.tensor(y, dtype=torch.long)      # Cross EntropyLoss에서는 long타입 필요
    
    def __len__(self):
        return len(self.X)
    def __getitem__(self, index):
        return self.X[index] , self.y[index]

In [79]:
# 커스텀 데이터셋으로 생성- 입력과 타겟을 하나로 묶음
train_dataset = IrisDataset(train_scaled, train_target)
val_dataset = IrisDataset(val_scaled, val_target)

In [80]:
#데이터로더로 생성- 배치학습, 셔플, 병렬데이터 로딩
train_loader = DataLoader(train_dataset, batch_size=16, shuffle = True)
val_loader = DataLoader(val_dataset, batch_size=16)

- 실제 모델 훈련에서는 데이터로더를 사용